### ISSUE TITLE
Estatística de url referer

### ISSUE THREAD

**Issue by webkoder** [webkoder/readlog#10]
Criar uma tabela separada para fazer a contagem de url referer durante o processamento

**Comment by webkoder** [comment]
O que a @DeiaMatos vai fazer....

- Tirar o campo **self.referer** do método **toTupla** da classe Contador
- Tirar as referências de referer no método **insert**
- Criar um método na classe **Contador** com os valores da tabela **acesso** em uma tupla
- Criar um método na classe **Orm** de insert na tabela **acesso**
- Fazer a chamada do novo insert no arquivo **main**

**Comment by DeiaMatos** [comment]
Tarefa realizada!
